### PR TITLE
fix: allow injecting JWT options when creating a VC fixes #89

### LINKED ISSUE #89: [BUG] Not possible to set expiresIn or canonicalize when creating a VC
Hello,
I was not able to create a VC with an expiry time. I see no way of setting the option `expiresIn` of the underlying library `did-jwt` because I cannot inject further options in the second argument.

```javascript
// did-jwt
export async function createJWT(
  payload: Partial<JWTPayload>,
  { issuer, signer, alg, expiresIn, canonicalize }: JWTOptions,
  header: Partial<JWTHeader> = {}
): Promise<string> { // ...
```
https://github.com/decentralized-identity/did-jwt-vc/blob/170ab4032720ac1358b5e0274c92a29cfd97c219/src/index.ts#L75-L85

Similarly, `canonicalize` in the JWTOptions (`did-jwt`) cannot be set.

### PR DESCRIPTION
**Pull request by nikolockenvitz**
I created a proposal to fix the bug described in #89. Happy to hear your feedback.

### CODE REVIEW

File: src/types.ts [hunk 1]
```diff
@@ -232,6 +232,12 @@ export interface CreateCredentialOptions {
    * If the issuer or holder does not list an `alg`, then the one specified in `header` will be used
    */
   header?: Partial<JWTHeader>
+
+  /**
+   * Allows including or overriding some header parameters for the resulting JWT.
+   */
+  jwt?: Partial<JWTOptions>
```
Comment (mirceanis) [inline src/types.ts:239]: I find this layering of options a little confusing.
Perhaps it would be easier to have:
```ts
export interface CreateCredentialOptions extends Partial<JWTOptions> {
```

And then call `createJWT` with `...options` instead of `...options.jwt`

**Review by mirceanis — COMMENTED** [review]
Please read my suggestion about the options layering.

Also, I guess options should also be propagated when creating presentations too, and then some tests added.

File: src/types.ts (hunk 1 above)
Comment (nikolockenvitz) [reply src/types.ts:239]: This would then also inject `options.removeOriginalFields` and `options.header` into the second argument of `createJWT`. Is this a problem?

Comment (mirceanis) [reply src/types.ts:239]: It's not a problem.
`createJWT` does not use those fields.

**Comment by nikolockenvitz** [comment]
I added a test to check whether the created VC has a correct `exp` set. I am not sure whether a test for `canonicalize` makes sense and how to do that with jest.

I updated the implementation as you suggested and also did the same for the Verifiable Presentation.
There, I was not sure whether a test makes sense because `iat` is explicitly set to `undefined` for VPs.

**Review by mirceanis — APPROVED** [review]
Excellent work!
Thank you for your contribution.
